# Generated by ./configure — do not edit
HAVE_AUDIO   = 1
AUDIO_CFLAGS = -DHAVE_AUDIO -DHAVE_PIPEWIRE -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -D_REENTRANT -fno-strict-aliasing -fno-strict-overflow -DHAVE_UDEV -DLIBUDEV_VERSION=\"259\" -DHAVE_LAME
AUDIO_SRCS   = audio.c
AUDIO_LIBS   = -lpipewire-0.3 -ludev -lmp3lame
RECORD_SRCS  = record.c
